lang:
  SPEED: "effect.minecraft.speed"
  SLOW: "effect.minecraft.slowness"
  FAST_DIGGING: "effect.minecraft.haste"
  SLOW_DIGGING: "effect.minecraft.mining_fatigue"
  INCREASE_DAMAGE: "effect.minecraft.strength"
  HEAL: "effect.minecraft.instant_health"
  HARM: "effect.minecraft.instant_damage"
  JUMP: "effect.minecraft.jump_boost"
  CONFUSION: "effect.minecraft.nausea"
  REGENERATION: "effect.minecraft.regeneration"
  DAMAGE_RESISTANCE: "effect.minecraft.resistance"
  FIRE_RESISTANCE: "effect.minecraft.fire_resistance"
  WATER_BREATHING: "effect.minecraft.water_breathing"
  INVISIBILITY: "effect.minecraft.invisibility"
  BLINDNESS: "effect.minecraft.blindness"
  NIGHT_VISION: "effect.minecraft.night_vision"
  HUNGER: "effect.minecraft.hunger"
  WEAKNESS: "effect.minecraft.weakness"
  POISON: "effect.minecraft.poison"
  WITHER: "effect.minecraft.wither"
  HEALTH_BOOST: "effect.minecraft.health_boost"
  ABSORPTION: "effect.minecraft.absorption"
  SATURATION: "effect.minecraft.saturation"
  GLOWING: "effect.minecraft.glowing"
  LUCK: "effect.minecraft.luck"
  UNLUCK: "effect.minecraft.unluck"
  LEVITATION: "effect.minecraft.levitation"
  SLOW_FALLING: "effect.minecraft.slow_falling"
  CONDUIT_POWER: "effect.minecraft.conduit_power"
  DOLPHINS_GRACE: "effect.minecraft.dolphins_grace"
  BAD_OMEN: "effect.minecraft.bad_omen"
  HERO_OF_THE_VILLAGE: "effect.minecraft.hero_of_the_village"

addText: " エフェクトを追加しました"
removeText: "エフェクトをすべて削除しました"
resetButtonText: "エフェクトをリセットする"